name: e_invoice_schema_generator
description: A command-line application to create schema classes from XML files.
version: 0.0.1

environment:
  sdk: ^3.4.3

dependencies:
  args: ^2.4.2
  code_builder: ^4.10.0
  dart_style: ^2.3.7
  path: ^1.9.0
  xml: ^6.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
